# Generated by Django 4.1.7 on 2023-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_accounts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_list',
            name='is_phone_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='accounts_list',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
