# Generated by Django 4.1.7 on 2023-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_accounts_list_is_phone_verified_accounts_list_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_list',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
