# Generated by Django 4.1.7 on 2023-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_accounts_list_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
