# Generated by Django 4.1.7 on 2023-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_accounts_list_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_list',
            name='Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='Mobile_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='aadhar',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='secret_question',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_list',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
