# Generated by Django 4.1.7 on 2023-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_accounts_list_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('entry_age', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('Annual_premium', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='accounts_list',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accounts_list',
            name='loan_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts_list',
            name='schemes',
            field=models.ManyToManyField(blank=True, null=True, to='registration.scheme'),
        ),
    ]
