# Generated by Django 4.1.7 on 2023-04-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_scheme_accounts_list_count_accounts_list_loan_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_list',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
