# Generated by Django 4.1.7 on 2023-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_accounts_list_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='in_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
