# Generated by Django 4.1.7 on 2023-04-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_scheme_in_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transac',
            name='oppo_acc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
